#!/bin/sh
set -eu

cd "$(git rev-parse --show-toplevel)"

cargo fmt --all -- --check

if [ -n "${RUSTFLAGS:-}" ]; then
  export RUSTFLAGS="$RUSTFLAGS -D warnings"
else
  export RUSTFLAGS="-D warnings"
fi

cargo clippy --all-targets --all-features -- -W clippy::pedantic
